---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sql
  namespace: {{ .Release.Namespace }}
spec:
  minReadySeconds: 30
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - image: {{.Values.mysql.imagename}}:{{ default .Chart.AppVersion .Values.mysql.imagetag }} #mysql:5.6
          name: mysql
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-vol
          env:
          - name: MYSQL_DATABASE
            value: {{ .Values.mysql.MYSQL_DATABASE }} #openmrs
          - name: MYSQL_USER
            value:  {{ .Values.mysql.MYSQL_USER }} #balajiazure
          - name: MYSQL_PASSWORD
            value: {{ .Values.mysql.MYSQL_PASSWORD }} #balajiazure
          - name: MYSQL_ROOT_PASSWORD
            value: {{ .Values.mysql.MYSQL_ROOT_PASSWORD }} #password
      volumes:
        - name: mysql-vol
          persistentVolumeClaim: 
            claimName: {{ .Release.Name }}-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sql #mysqlsvc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: db
  type: ClusterIP
  ports:
    - port: 3306
